Repository axa-ch-webhub-cloud/pattern-library, pull requests merged in 2018-03, with the labels that each got.

#292 Bugfix/ios landscape mobile navi button
  src/components/m-header-mobile-navigation/index.scss
  src/styles/mixins/_hardware-accelerate.scss
Labels: bug, high-prio, ios

#296 adding x and y args
  src/styles/mixins/_hardware-accelerate.scss
Labels: enhancement

#295 fixed logi link width
  src/components/m-header-logo/index.scss
Labels: bug, low-prio

#298 fixed eslint
  src/js/has-passive.js
Labels: bug, high-prio

#300 Bugfix/buttons out transition broken
  src/components/m-button/mixins/_button.scss
  src/components/m-button/settings/_button.scss
Labels: bug, high-prio

#301 added text transition to buttons
  src/components/m-button/mixins/_button.scss
Labels: enhancement, high-prio

#305 Bugfix/edge stroke animation
  dist/components/m-header-navigation/index.js
  dist/components/m-header-navigation/index.umd.js
  dist/components/m-header-sub-navigation/index.js
  dist/components/m-header-sub-navigation/index.umd.js
  dist/index.html
  docs/components/m-header-navigation/index.js
  docs/components/m-header-navigation/index.umd.js
  docs/components/m-header-sub-navigation/index.js
  docs/components/m-header-sub-navigation/index.umd.js
  docs/index.html
  src/components/m-header-navigation/js/header-sub-navigation.js
  src/components/m-header-navigation/js/stroke.js
  src/components/m-header-navigation/styles/_stroke.scss
  src/components/m-header-sub-navigation/index.js
  src/js/force-repaint.js
Labels: bug, high-prio

#307 added extra delay
  src/components/m-header-navigation/js/header-sub-navigation.js
Labels: bug, high-prio

#308 make sure to wait for next paint
  src/components/m-header-navigation/js/header-sub-navigation.js
Labels: bug, high-prio

#310 should fixed wtf bug
  src/components/m-header-navigation/js/header-sub-navigation.js
Labels: bug, high-prio

#311 hope this fixes edge not repainting on enter
  src/components/m-header-navigation/js/header-sub-navigation.js
Labels: bug, high-prio

#319 renamed use default event
  src/components/m-header-mobile-navigation/js/header-mobile-navigation.js
  src/components/m-header-navigation/js/header-sub-navigation.js
  src/components/m-header-navigation/js/stroke.js
  src/js/ui-events.js
Labels: bug, high-prio

#323 fixed name
  CONTRIBUTING.md
  README.md
Labels: bug, high-prio

#329 Feature/add pr template
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement, high-prio

#328 start adding issue template
  ISSUE_TEMPLATE.md
Labels: enhancement, high-prio

#338 add small dropdown
  src/components/m-dropdown/_preview.html
  src/components/m-dropdown/_template.js
  src/components/m-dropdown/index.js
  src/components/m-dropdown/index.scss
  src/components/m-dropdown/mixins/dropdown.scss
  src/components/m-dropdown/settings/dropdown.scss
Labels: enhancement, high-prio

#341 add axa container
  src/components/m-container/_example.html
  src/components/m-container/_preview.html
  src/components/m-container/_template.js
  src/components/m-container/index.js
  src/components/m-container/index.scss
Labels: enhancement, high-prio

#343 fixed missing overflow hidden
  src/components/m-header-mobile-navigation/index.scss
Labels: bug, low-prio

#345 Bugfix/stroke accesses parents directly
  src/components/m-header-main/index.js
  src/components/m-header-navigation/index.js
  src/components/m-header-navigation/js/stroke.js
  src/js/ui-events.js
Labels: bug, high-prio

#349 Bugfix/bel deprecated
  CONTRIBUTING.md
  package.json
  src/components/a-icon/_template.js
  src/components/a-typo/_template.js
  src/components/m-accordion-item/_template.js
  src/components/m-accordion/_template.js
  src/components/m-button/_template.js
  src/components/m-container/_template.js
  src/components/m-dropdown/_template.js
  src/components/m-footer-languages/_template.js
  src/components/m-footer-links/_template.js
  src/components/m-footer-main/_template.js
  src/components/m-footer-social/_template.js
  src/components/m-footer-sub/_template.js
  src/components/m-header-burger/_template.js
  src/components/m-header-languages/_template.js
  src/components/m-header-logo/_template.js
  src/components/m-header-main/_template.js
  src/components/m-header-meta-right/_template.js
  src/components/m-header-meta/_template.js
  src/components/m-header-mobile-languages/_template.js
  src/components/m-header-mobile-navigation/_template.js
  src/components/m-header-mobile-others/_template.js
  src/components/m-header-mobile/_template.js
  src/components/m-header-navigation/_template.js
  src/components/m-header-others/_template.js
  src/components/m-header-search/_template.js
  src/components/m-header-sub-navigation/_template.js
  src/components/m-header-top-content-bar/_template.js
  src/components/m-link/_template.js
  src/components/o-sticky/sticky.template.js
  stack/tasks/create-a-m-o.js
Labels: bug, high-prio

#348 restructure global scss folder
  src/app/_preview.scss
  src/components/a-device-state/index.scss
  src/components/a-typo/index.scss
  src/components/a-vertical-rhythm/index.scss
  src/components/m-accordion-item/index.scss
  src/components/m-button/mixins/_button.scss
  src/components/m-container/index.scss
  src/components/m-dropdown/index.scss
  src/components/m-footer-languages/index.scss
  src/components/m-footer-legals/index.scss
  src/components/m-footer-links/index.scss
  src/components/m-footer-main/index.scss
  src/components/m-footer-social/index.scss
  src/components/m-footer-sub/index.scss
  src/components/m-header-languages/index.scss
  src/components/m-header-logo/index.scss
  src/components/m-header-main/index.scss
  src/components/m-header-meta-right/index.scss
  src/components/m-header-meta/index.scss
  src/components/m-header-mobile-languages/index.scss
  src/components/m-header-mobile-navigation/index.scss
  src/components/m-header-mobile-others/index.scss
  src/components/m-header-navigation/index.scss
  src/components/m-header-others/index.scss
  src/components/m-header-sub-navigation/index.scss
  src/components/m-header-top-content-bar/index.scss
  src/components/m-link/mixins/_link.scss
  src/styles/_fonts.scss
  src/styles/functions/_breakpoint.scss
  src/styles/functions/_grid.scss
  src/styles/functions/_typo.scss
  src/styles/grid/_grid.functions.scss
  src/styles/grid/_grid.mixins.scss
  src/styles/grid/_grid.settings.scss
  src/styles/mixins/_fonts.scss
  src/styles/mixins/_grid.scss
  src/styles/mixins/_icon.scss
  src/styles/mixins/_respond.scss
  src/styles/mixins/_size.scss
  src/styles/mixins/_typo.scss
  src/styles/mixins/_vertical-rhythm.scss
  src/styles/mixins/_visibility.scss
  src/styles/settings/_fonts.scss
  src/styles/settings/_grid.scss
  src/styles/settings/_vertical-rhythm.scss
  src/styles/typo/_typo.functions.scss
  src/styles/typo/_typo.mixins.scss
  src/styles/typo/_typo.settings.scss
  src/styles/typo/_typo.webfonts.scss
  src/styles/vertical-rhythm/_vertical-rhythm.mixins.scss
  src/styles/vertical-rhythm/_vertical-rhythm.settings.scss
Labels: bug, high-prio

#352 added missing babelrc conf as mentioned in the docs
  .babelrc
  src/components/a-icon/_template.js
Labels: bug, high-prio

#354 Bugfix/axa icon dont use
  src/components/a-icon/_preview.html
  src/components/a-icon/_template.js
  src/components/m-accordion-item/_template.js
  src/components/m-button/_template.js
  src/components/m-dropdown/_template.js
  src/components/m-footer-links/_template.js
  src/components/m-footer-social/_template.js
  src/components/m-header-burger/_template.js
  src/components/m-header-languages/_template.js
  src/components/m-header-logo/_template.js
  src/components/m-header-mobile-navigation/_template.js
  src/components/m-header-search/_template.js
  src/components/m-header-sub-navigation/_template.js
  src/components/m-link/_template.js
Labels: bug, high-prio

#358 updated nanohtml
  package.json
Labels: bug, high-prio

#360 updated release script to refelct develop trunk
  stack/tasks/release.js
Labels: enhancement, high-prio

#361 updated info texts
  stack/tasks/release.js
Labels: bug, high-prio

#362 should be 4 not 3
  stack/tasks/release.js
Labels: bug, high-prio

#368 crazy fix for edge 16 ohoooo
  src/components/m-header-navigation/js/header-navigation.js
Labels: bug, high-prio

#340 enable re-rendering
  .eslintrc
  src/components/_abstract/component-types.js
  src/components/a-checkbox/index.js
  src/components/a-device-state/index.js
  src/components/a-icon/_preview.html
  src/components/a-icon/index.js
  src/components/a-radio/index.js
  src/components/a-typo/index.js
  src/components/a-vertical-rhythm/index.js
  src/components/m-accordion-item/index.js
  src/components/m-accordion/index.js
  src/components/m-button/index.js
  src/components/m-container/index.js
  src/components/m-dropdown/index.js
  src/components/m-footer-languages/index.js
  src/components/m-footer-legals/index.js
  src/components/m-footer-links/index.js
  src/components/m-footer-main/index.js
  src/components/m-footer-social/index.js
  src/components/m-footer-sub/index.js
  src/components/m-header-burger/index.js
  src/components/m-header-languages/index.js
  src/components/m-header-logo/index.js
  src/components/m-header-main/index.js
  src/components/m-header-meta-right/index.js
  src/components/m-header-meta/index.js
  src/components/m-header-mobile-languages/index.js
  src/components/m-header-mobile-navigation/index.js
  src/components/m-header-mobile-others/index.js
  src/components/m-header-mobile/index.js
  src/components/m-header-navigation/_template.js
  src/components/m-header-navigation/index.js
  src/components/m-header-navigation/js/stroke.js
  src/components/m-header-others/index.js
  src/components/m-header-search/index.js
  src/components/m-header-sub-navigation/_preview.html
  src/components/m-header-sub-navigation/_template.js
  src/components/m-header-sub-navigation/index.js
  src/components/m-header-top-content-bar/index.js
  src/components/m-link/index.js
  src/components/o-footer/index.js
  src/components/o-header/index.js
  src/components/o-sticky/index.js
  src/js/abstract/base-component-global.js
  src/js/abstract/base-component-shadow.js
  src/js/abstract/base-component.js
  src/js/abstract/component-types.js
  src/js/get-attribute.js
  src/js/maybe.js
  src/js/toProp.js
  src/js/ui-events.js
  stack/tasks/bundles/_common.js
  stack/tasks/create-a-m-o.js
Labels: bug, high-prio

#375 fixed replacements not strings
  stack/tasks/bundles/_common.js
Labels: bug, high-prio

#378 fixed eslint errors
  .eslintrc
Labels: bug, high-prio

#356 Bugfix/fix props vs attrs
  src/components/a-checkbox/index.js
  src/components/a-icon/_preview.html
  src/components/a-icon/_template.js
  src/components/a-icon/index.js
  src/components/a-radio/index.js
  src/components/m-dropdown/_template.js
  src/components/m-dropdown/index.js
  src/components/m-footer-languages/_template.js
  src/components/m-footer-languages/index.js
  src/components/m-footer-links/_template.js
  src/components/m-footer-links/index.js
  src/components/m-footer-social/_template.js
  src/components/m-footer-social/index.js
  src/components/m-header-languages/_template.js
  src/components/m-header-main/index.js
  src/components/m-header-mobile-languages/_template.js
  src/components/m-header-mobile-navigation/_template.js
  src/components/m-header-mobile-navigation/index.js
  src/components/m-header-mobile-others/_template.js
  src/components/m-header-mobile/_template.js
  src/components/m-header-mobile/index.js
  src/components/m-header-navigation/_template.js
  src/components/m-header-navigation/index.js
  src/components/m-header-others/_template.js
  src/components/m-header-sub-navigation/_template.js
  src/components/m-header-sub-navigation/index.js
  src/components/m-header-top-content-bar/index.js
  src/components/o-sticky/index.js
  src/js/abstract/base-component.js
  src/js/abstract/property-exists-exception.js
  src/js/get-attribute.js
  src/js/to-prop.js
Labels: bug, high-prio

#351 refactored classlist functions to support multiple class names
  src/components/m-header-navigation/js/stroke.js
  src/js/class-list.js
Labels: enhancement, high-prio

#379 Feature/add component docs
  CONTRIBUTING.md
  README.md
  src/js/abstract/base-component.js
Labels: enhancement, high-prio
