Repository axa-ch-webhub-cloud/pattern-library, pull requests merged in 2018-11, with the labels that each got.

#649 should make it a lot easier
  src/js/abstract/hocs/with-render.js
  src/js/abstract/hocs/with-update.js
  src/js/abstract/utils/property-exists-exception.js
Labels: bug, high-prio

#639 updated create amo file and contribution file
  CONTRIBUTING.md
  stack/tasks/create-a-m-o.js
Labels: bug, high-prio, not reviewed within 48 hours

#665 Bugfix/attribute changed broken
  src/components/a-choice/index.js
  src/components/a-input/index.js
  src/components/a-radio/index.js
  src/components/m-col/index.js
  src/components/m-datepicker-body/index.js
  src/components/m-dropdown/index.js
  src/components/m-footer-languages/index.js
  src/components/m-footer-links/index.js
  src/components/m-footer-social/index.js
  src/components/m-form-group/index.js
  src/components/m-header-main/index.js
  src/components/m-header-mobile-navigation/index.js
  src/components/m-header-navigation/index.js
  src/components/m-header-sub-navigation/index.js
  src/components/m-header-top-content-bar/index.js
  src/components/m-row/index.js
  src/components/m-sticky/index.js
  src/components/o-error-page/index.js
  src/components/o-sticky-container/index.js
  src/js/abstract/hocs/with-update.js
  src/js/prop-types/prop-types.js
Labels: bug, high-prio

#666 Bugfix/broken with react since props refactor
  src/components/m-footer-links/js/footer-links.js
  src/js/abstract/hocs/with-update.js
Labels: bug, high-prio

#685 fix(with-react): broken built-ins
  src/js/with-react.js
Labels: bug, high-prio

#686 fix(polyfill): upgrade built-in polyfill
  README.md
  package.json
  src/app/app.js
Labels: enhancement, high-prio

#689 fix(with-react): broken built-in native attribute features
  src/js/with-react.js
Labels: bug, high-prio

#692 fix(built-in): broken safari, never use constructor
  CONTRIBUTING.md
  src/js/abstract/hocs/with-base.js
  src/js/abstract/hocs/with-update.js
Labels: bug, high-prio

#694 Feature/add version flag
  .babelrc
  CONTRIBUTING.md
  package.json
  src/js/abstract/hocs/index.js
  src/js/abstract/hocs/with-version.js
Labels: enhancement, high-prio

#700 Bugfix/use relative urls
  stack/tasks/build-examples.js
Labels: bug, high-prio, merged without review

#703 fixing datepicker & hero cover & home Button
  src/app/single-component.html
  src/components/m-datepicker/index.scss
  src/components/o-commercial-hero-cover/index.scss
Labels: PROD_ISSUE, bug, high-prio, merged without review

#704 add styles in prod again
  stack/tasks/build-examples.js
Labels: PROD_ISSUE, bug, high-prio

#707 Update readme
  README.md
Labels: enhancement

#708 fixed header buttons
  src/app/index.html
  src/app/partials/header.html
  src/app/single-component.html
  src/components/m-header-meta-right/_preview.html
  src/components/m-header-mobile/_preview.html
  src/components/m-header-mobile/index.scss
  src/components/m-header-top-content-bar/_preview.html
  src/components/o-header/_preview.html
  stack/tasks/build-examples.js
Labels: breaking changes, enhancement

#711 fix mobile as well
  src/app/partials/header.html
Labels: PROD_ISSUE, bug, high-prio, merged without review
