Repository axa-ch-webhub-cloud/pattern-library, pull requests merged in 2018-10, with the labels that each got.

#577 Feature/add react exports
  src/components/m-header-sub-navigation/index.js
  src/components/o-sticky/index.js
  src/js/react-exports.js
  stack/tasks/create-a-m-o.js
Labels: enhancement, high-prio

#578 add all components in one native exports
  package.json
  src/index.js
  stack/tasks/create-a-m-o.js
Labels: enhancement, high-prio

#580 enabled no important rule
  .stylelintrc
  src/app/_preview.scss
  src/components/a-input/index.scss
  src/components/m-button/mixins/_button.scss
  src/components/m-dropdown/mixins/dropdown.scss
  src/components/m-footer-languages/index.scss
  src/components/m-footer-legals/index.scss
  src/components/m-footer-links/index.scss
  src/components/m-footer-social/index.scss
  src/components/m-header-main/index.scss
  src/components/m-header-main/settings/_header-main.scss
  src/components/m-header-mobile/index.scss
  src/components/m-header-navigation/js/stroke.js
  src/components/m-header-navigation/styles/_stroke.scss
  src/components/m-header-sub-navigation/index.scss
  src/components/m-header-top-content-bar/index.scss
  src/components/m-link/mixins/_link.scss
  src/styles/mixins/_visibility.scss
Labels: enhancement, high-prio

#585 Feature/add prop types
  CONTRIBUTING.md
  package.json
  src/app/es6-polyfills.js
  src/components/a-checkbox/index.js
  src/components/a-choice/index.js
  src/components/a-icon/index.js
  src/components/a-input/index.js
  src/components/a-radio/_preview.html
  src/components/a-radio/index.js
  src/components/m-accordion-item/index.js
  src/components/m-button/index.js
  src/components/m-col/index.js
  src/components/m-datepicker-body/index.js
  src/components/m-datepicker/_template.js
  src/components/m-datepicker/index.js
  src/components/m-dropdown/index.js
  src/components/m-footer-languages/index.js
  src/components/m-footer-legals/index.js
  src/components/m-footer-links/index.js
  src/components/m-footer-main/index.js
  src/components/m-footer-social/index.js
  src/components/m-form-group/_preview.html
  src/components/m-form-group/index.js
  src/components/m-header-languages/index.js
  src/components/m-header-logo/index.js
  src/components/m-header-main/index.js
  src/components/m-header-mobile-languages/index.js
  src/components/m-header-mobile-navigation/index.js
  src/components/m-header-mobile-others/index.js
  src/components/m-header-mobile/index.js
  src/components/m-header-navigation/index.js
  src/components/m-header-others/index.js
  src/components/m-header-search/index.js
  src/components/m-header-sub-navigation/index.js
  src/components/m-header-top-content-bar/index.js
  src/components/m-link/index.js
  src/components/m-policy-feature-item/index.js
  src/components/m-row/index.js
  src/components/o-commercial-hero-cover/index.js
  src/components/o-container/index.js
  src/components/o-cookie-disclaimer/index.js
  src/components/o-datepicker/index.js
  src/components/o-error-page/index.js
  src/components/o-header/_preview.html
  src/components/o-policy-features/index.js
  src/components/o-sticky/index.js
  src/components/o-testimonials/index.js
  src/js/abstract/hocs/with-update.js
  src/js/get-base-uri.js
  src/js/lazy-function.js
  src/js/prop-types/index.js
  src/js/prop-types/is-required-helper.js
  src/js/prop-types/locale-prop-type.js
  src/js/prop-types/url-prop-type.js
  src/js/prop-types/value-prop-type.js
  stack/tasks/create-a-m-o.js
Labels: enhancement, high-prio

#594 bugfix icon root node no class
  src/components/a-icon/index.js
  src/components/a-icon/index.scss
  src/js/abstract/hocs/with-update.js
  src/js/abstract/utils/morph.js
Labels: bug, high-prio

#481 Bugfix/button icon only
  src/components/m-button/_preview.html
  src/components/m-button/_template.js
  src/components/m-button/index.scss
  src/components/m-button/mixins/_button.scss
  src/components/m-button/settings/_button.scss
  src/js/is-empty-fragment.js
Labels: bug, low-prio

#597 improved attribute change check
  src/js/abstract/utils/morph.js
Labels: bug, high-prio

#598 added min height to button
  src/components/m-button/mixins/_button.scss
Labels: bug, high-prio

#606 fix event on axa change
  src/components/m-datepicker-body/js/datepicker-body.js
  src/components/m-datepicker/js/datepicker.js
  src/components/o-datepicker/js/datepicker.js
  src/demos/todomvc/todos.jsx
Labels: enhancement, high-prio, merged without review

#614 fix month index in parseLocalisedDateIfValid()
  src/demos/todomvc/todos.jsx
  src/js/date.js
Labels: bug, high-prio

#618 fix month index when opening axa-m-datepicker in axa-datepicker
  src/components/m-datepicker/_template.js
  src/components/m-datepicker/index.js
  src/components/o-datepicker/_template.js
Labels: bug

#622 Feature/landingpage design improvements
  .gitignore
  src/components/o-commercial-hero-cover/_preview.html
  src/components/o-commercial-hero-cover/index.scss
  src/components/o-policy-features/index.scss
  src/components/o-testimonials/index.scss
  src/styles/grid/_grid-settings.scss
Labels: enhancement

#628 Bugfix/some dropdown issues
  src/components/m-dropdown/_preview.html
  src/components/m-dropdown/_template.js
  src/js/abstract/hocs/with-update.js
  src/js/get-attribute.js
  src/js/get-attributes.js
  src/js/to-prop.js
Labels: bug, high-prio

#629 Bugfix/fix boolean prop type
  src/js/get-attribute.js
  src/js/to-prop.js
Labels: bug, high-prio

#633 Bugfix/forget to shim is required
  src/js/get-attribute.js
  src/js/prop-types/prop-types.js
  src/js/to-prop.js
Labels: bug, high-prio
