Repository axa-ch-webhub-cloud/pattern-library, pull requests merged in 2019-02, with the labels that each got.

#808 Added readonly option to input and preview improvements.
  src/components/a-input/_preview.html
  src/components/a-input/_template.js
  src/components/a-input/index.d.ts
  src/components/a-input/index.js
  src/components/a-input/index.scss
Labels: PROD_ISSUE, enhancement, high-prio

#824 Bugfix/grid inconsistencies
  src/components/m-col/index.js
  src/styles/grid/_grid-framework.scss
Labels: PROD_ISSUE, bug, high-prio, not reviewed within 48 hours

#840 Fix broken icons in button, fixes #836
  src/components/m-button/index.scss
Labels: PROD_ISSUE, bug, high-prio
