Repository axa-ch-webhub-cloud/pattern-library, pull requests merged in 2019-05, with the labels that each got.

#937 Feature/prettier into pipeline ( ͡ ͜ʖ ͡°)
  .eslintrc
  .prettierignore
  .prettierrc
  .storybook/.babelrc.js
  .storybook/addons/markdown.js
  .storybook/config.js
  .storybook/preview-head.html
  .storybook/webpack.config.js
  ARCHITECTURE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTION.md
  FOUNDATION.md
  README.md
  WAYS_OF_WORKING.md
  config/jest/jestPreprocess.js
  jest.config.js
  package.json
  rollup.config.js
  scripts/build.icon-set.js
  scripts/build.materials.js
  scripts/build.test.js
  scripts/create-a-m-o/functions.js
  scripts/create-a-m-o/templates/template-package.json
  scripts/test.unit.js
  src/components/10-atoms/button-link/index.js
  src/components/10-atoms/button-link/story.js
  src/components/10-atoms/button-link/ui.test.js
  src/components/10-atoms/button/index.js
  src/components/10-atoms/button/story.js
  src/components/10-atoms/button/ui.test.js
  src/components/10-atoms/icon/index.js
  src/components/10-atoms/icon/index.react.js
  src/components/10-atoms/icon/story.js
  src/components/10-atoms/icon/ui.test.js
  src/components/10-atoms/link/story.js
  src/components/10-atoms/link/ui.test.js
  src/components/20-molecules/datepicker/index.js
  src/components/20-molecules/datepicker/test.accessor.js
  src/components/20-molecules/datepicker/ui.test.js
  src/components/20-molecules/datepicker/utils/Cell.js
  src/components/20-molecules/datepicker/utils/Store.js
  src/components/20-molecules/datepicker/utils/date.js
  src/components/20-molecules/dropdown/index.js
  src/components/20-molecules/dropdown/utils/debounce.js
  src/components/20-molecules/footer-small/index.js
  src/components/20-molecules/footer-small/story.js
  src/components/20-molecules/footer-small/ui.test.js
  src/demo/demo-controlled-inputs/App.jsx
  src/demo/demo-controlled-inputs/customelements/check-box.js
  src/demo/demo-controlled-inputs/customelements/drop-down.js
  src/demo/demo-controlled-inputs/customelements/radio-button.js
  src/demo/demo-controlled-inputs/customelements/text-area.js
  src/demo/demo-controlled-inputs/customelements/text-input.js
  src/demo/demo-dynamic-children/App.jsx
  src/demo/demo-dynamic-children/customelements/my-table.js
  src/demo/footer-small/FooterSmall.jsx
  src/demo/react/DemoButton.jsx
  src/demo/react/DemoIcon.jsx
Labels: V2

#935 Feature/axa link with variants
  src/components/10-atoms/link/README.md
  src/components/10-atoms/link/index.js
  src/components/10-atoms/link/index.scss
  src/components/10-atoms/link/story.js
  src/components/10-atoms/link/ui.test.js
Labels: V2

#939 Feature/demo improvements
  .eslintrc
  .storybook/config.js
Labels: V2

#917 The AXA TABLE
  .gitignore
  .npmignore
  package.json
  rollup.config.js
  scripts/finalise.build.js
  src/components/20-molecules/.gitkeep
  src/components/30-organisms/.gitkeep
  src/components/30-organisms/table-sortable/README.md
  src/components/30-organisms/table-sortable/index.js
  src/components/30-organisms/table-sortable/index.react.js
  src/components/30-organisms/table-sortable/index.scss
  src/components/30-organisms/table-sortable/package.json
  src/components/30-organisms/table-sortable/story.js
  src/components/30-organisms/table-sortable/ui.test.js
  src/components/30-organisms/table/README.md
  src/components/30-organisms/table/index.js
  src/components/30-organisms/table/index.react.js
  src/components/30-organisms/table/index.scss
  src/components/30-organisms/table/package.json
  src/components/30-organisms/table/story.js
  src/components/30-organisms/table/ui.test.js
  src/demo/react/DemoTable.jsx
  src/demo/react/story.jsx
Labels: V2

#942 Add dist to everyone
  package.json
  rollup.config.js
  scripts/create-a-m-o/templates/template-package.json
  src/components/00-materials/package.json
  src/components/10-atoms/button-link/package.json
  src/components/10-atoms/button/package.json
  src/components/10-atoms/icon/package.json
  src/components/20-molecules/datepicker/package.json
  src/components/20-molecules/footer-small/package.json
  src/components/30-organisms/table-sortable/package.json
  src/components/30-organisms/table/package.json
Labels: V2, bug, high-prio

#944 Feature/button demos
  .storybook/addons.js
  .storybook/addons/reset-body.js
  CONTRIBUTION.md
  README.md
  config/globals.js
  src/components/00-materials/00-colors.scss
  src/components/00-materials/30-layout.scss
  src/components/10-atoms/button/README.md
  src/components/10-atoms/button/demo.js
  src/components/10-atoms/button/index.js
  src/components/10-atoms/button/index.scss
  src/components/10-atoms/button/react/AXAButtonReact.jsx
  src/components/10-atoms/button/react/DemoButtonClick.jsx
  src/components/10-atoms/button/react/DemoButtonForm.jsx
  src/components/10-atoms/button/react/demo.jsx
  src/components/10-atoms/button/react/story.jsx
  src/components/10-atoms/button/story.js
  src/components/10-atoms/button/ui.test.js
Labels: V2

#945 Feature/update prettier and exclude project root
  .eslintrc
  .prettierignore
  package.json
Labels: V2

#946 Feature/button link demos
  src/components/10-atoms/button-link/README.md
  src/components/10-atoms/button-link/demo.js
  src/components/10-atoms/button-link/index.js
  src/components/10-atoms/button-link/index.scss
  src/components/10-atoms/button-link/react/AXAButtonLinkReact.jsx
  src/components/10-atoms/button-link/react/DemoButtonLinkClick.jsx
  src/components/10-atoms/button-link/react/demo.jsx
  src/components/10-atoms/button-link/react/story.jsx
  src/components/10-atoms/button-link/story.js
  src/components/10-atoms/button-link/ui.test.js
  src/demo/react/DemoButton.jsx
  src/demo/react/story.jsx
Labels: V2

#943 Feature/release axa link
  src/components/10-atoms/link/index.js
  src/components/10-atoms/link/index.react.d.ts
  src/components/10-atoms/link/index.react.js
  src/components/10-atoms/link/package.json
Labels: V2

#948 Add react types to scaffolding script
  scripts/create-a-m-o/functions.js
Labels: V2

#949 Add description to Table Sortable
  src/components/30-organisms/table-sortable/README.md
  src/components/30-organisms/table/README.md
Labels: V2

#934 Feature/monkey patch remove and replace child
  CONTRIBUTING.md
  src/js/abstract/hocs/with-monkey-patches.js
  src/js/is-document-fragment.js
Labels: enhancement, high-prio, not reviewed within 48 hours

#950 Improve icon component readmes button, button link, materials
  package.json
  src/components/00-materials/README.md
  src/components/10-atoms/button-link/README.md
  src/components/10-atoms/button-link/package.json
  src/components/10-atoms/button-link/story.js
  src/components/10-atoms/button/README.md
  src/components/10-atoms/button/package.json
  src/components/10-atoms/icon/README.md
  src/components/10-atoms/icon/index.js
  src/components/10-atoms/icon/index.react.js
  src/components/10-atoms/icon/package.json
  src/components/10-atoms/icon/ui.test.js
  src/demo/react/DemoIcon.jsx
  src/demo/react/story.jsx
Labels: V2

#962 Fix styleguides issues
  src/components/10-atoms/button-link/README.md
  src/components/10-atoms/button-link/index.js
  src/components/10-atoms/button-link/index.scss
  src/components/10-atoms/button-link/react/story.jsx
  src/components/10-atoms/button-link/story.js
  src/components/10-atoms/button/README.md
  src/components/10-atoms/button/index.js
  src/components/10-atoms/button/index.scss
  src/components/10-atoms/button/react/story.jsx
  src/components/10-atoms/button/story.js
Labels: V2

#955 Develop v2 no shadow dom base class
  package.json
  src/components/30-organisms/table-sortable/index.js
  src/components/30-organisms/table-sortable/ui.test.js
  src/components/30-organisms/table/index.js
  src/components/30-organisms/table/index.scss
  src/components/30-organisms/table/ui.test.js
  src/demo/react/DemoTable.jsx
  src/utils/no-shadow.js
Labels: V2

#967 Fix table resize
  src/components/30-organisms/table-sortable/ui.test.js
  src/components/30-organisms/table/ui.test.js
Labels: V2

#968 Release/v2 alpha bump
  src/components/00-materials/package.json
  src/components/05-utils/polyfill/package.json
  src/components/10-atoms/button-link/package.json
  src/components/10-atoms/button/package.json
  src/components/10-atoms/icon/package.json
  src/components/10-atoms/link/package.json
  src/components/20-molecules/datepicker/package.json
  src/components/20-molecules/dropdown/package.json
  src/components/20-molecules/footer-small/package.json
  src/components/30-organisms/table-sortable/package.json
  src/components/30-organisms/table/package.json
Labels: V2

#969 Add missing inputfield to datepicker react version
  src/components/20-molecules/datepicker/index.react.js
  src/components/20-molecules/datepicker/react/story.jsx
Labels: V2

#970 Publish
  src/components/00-materials/package.json
  src/components/05-utils/polyfill/package.json
  src/components/10-atoms/button-link/package.json
  src/components/10-atoms/button/package.json
  src/components/10-atoms/icon/package.json
  src/components/10-atoms/link/package.json
  src/components/20-molecules/datepicker/package.json
  src/components/20-molecules/dropdown/package.json
  src/components/20-molecules/footer-small/package.json
  src/components/30-organisms/table-sortable/package.json
  src/components/30-organisms/table/package.json
Labels: V2

#972 Feature/refactor link readme
  src/components/10-atoms/button-link/README.md
  src/components/10-atoms/button/README.md
  src/components/10-atoms/link/README.md
Labels: V2

#971 Feature/refactor footer stories
  src/components/20-molecules/footer-small/README.md
  src/components/20-molecules/footer-small/demo.js
  src/components/20-molecules/footer-small/index.scss
  src/components/20-molecules/footer-small/react/FooterSmall.jsx
  src/components/20-molecules/footer-small/react/story.jsx
  src/components/20-molecules/footer-small/story.js
  src/components/20-molecules/footer-small/ui.test.js
  src/demo/react/story.jsx
Labels: V2

#973 Add callback onAXADateChange prop
  src/components/20-molecules/datepicker/README.md
  src/components/20-molecules/datepicker/index.js
  src/components/20-molecules/datepicker/index.react.js
  src/components/20-molecules/datepicker/react/story.jsx
Labels: V2

#974 Adapt readme's
  src/components/00-materials/package.json
  src/components/10-atoms/button-link/package.json
  src/components/10-atoms/button/package.json
  src/components/10-atoms/icon/README.md
  src/components/10-atoms/icon/package.json
  src/components/20-molecules/datepicker/package.json
  src/components/20-molecules/dropdown/package.json
  src/components/30-organisms/table-sortable/package.json
  src/components/30-organisms/table/package.json
Labels: V2

#975 Bugfix/dropdown callbacks
  src/components/20-molecules/dropdown/README.md
  src/components/20-molecules/dropdown/index.js
  src/components/20-molecules/dropdown/index.react.js
  src/components/20-molecules/dropdown/react/story.jsx
Labels: V2

#980 Feature/enhance travis
  .travis.yml
  package.json
Labels: V2

#936 feat(footer-small): add TS type declaration file index.react.d.ts
  src/components/20-molecules/footer-small/index.react.d.ts
Labels: V2

#958 Add release docu
  CONTRIBUTION.md
Labels: V2

#976 Publish
  src/components/00-materials/package.json
  src/components/05-utils/polyfill/package.json
  src/components/10-atoms/button-link/package.json
  src/components/10-atoms/button/package.json
  src/components/10-atoms/icon/package.json
  src/components/10-atoms/link/package.json
  src/components/20-molecules/datepicker/package.json
  src/components/20-molecules/dropdown/package.json
  src/components/20-molecules/footer-small/package.json
  src/components/30-organisms/table-sortable/package.json
  src/components/30-organisms/table/package.json
Labels: V2
